config/routes.rb
Register::Application.routes.draw do
  resources :dependents

  root "welcome#index"

  devise_for :users, :controllers => { :sessions => "sessions", :registrations => "registrations" }

end

app/models/dependent.rb
class Dependent < ActiveRecord::Base
  # Validates first name and should not be blank
  validates :first_name, presence: true
  # Validates first name and should not be blank
  validates :last_name, presence: true
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :dependents
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/dependents_controller.rb
class DependentsController < ApplicationController
  before_action :set_dependent, only: [:show, :edit, :update, :destroy]
  # before_action :authenticate_user!

  # GET /dependents
  # GET /dependents.json
  def index
    @dependents = Dependent.all
  end

  # GET /dependents/1
  # GET /dependents/1.json
  def show
  end

  # GET /dependents/new
  def new
    @dependent = Dependent.new
  end

  # GET /dependents/1/edit
  def edit
  end

  # POST /dependents
  # POST /dependents.json
  def create
    @dependent = Dependent.new(dependent_params)

    respond_to do |format|
      if @dependent.save
        format.html { redirect_to @dependent, notice: 'Dependent was successfully created.' }
        format.json { render action: 'show', status: :created, location: @dependent }
      else
        format.html { render action: 'new' }
        format.json { render json: @dependent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dependents/1
  # PATCH/PUT /dependents/1.json
  def update
    respond_to do |format|
      if @dependent.update(dependent_params)
        format.html { redirect_to @dependent, notice: 'Dependent was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @dependent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dependents/1
  # DELETE /dependents/1.json
  def destroy
    @dependent.destroy
    respond_to do |format|
      format.html { redirect_to dependents_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dependent
      @dependent = Dependent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dependent_params
      params.require(:dependent).permit(:first_name, :last_name, :date_of_birth, :user_id)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    # if user_signed_in?
    #   redirect_to dependents_path and return
    # end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dependents_helper.rb
module DependentsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/dependents/_form.html.haml
= form_for(@dependent, :html=> {"data-abide"=>"" }) do |f|
  - if @dependent.errors.any?
    #error_explanation
      %h2= "#{pluralize(@dependent.errors.count, "error")} prohibited this dependent from being saved:"
      %ul
        - @dependent.errors.full_messages.each do |msg|
          %li= msg

  .row
    .large-3.columns
      = f.label :first_name
      = f.text_field :first_name,pattern: "[a-zA-Z]+", required: ''
      %small.error Firstname is required and must be a string.
    .large-3.columns
      = f.label :last_name
      = f.text_field :last_name,pattern: "[a-zA-Z]+", required: ''
      %small.error Lastname is required and must be a string.
    .large-3.columns
      = f.label :date_of_birth
      = f.text_field :date_of_birth, class: 'datepicker'
    = f.hidden_field :user_id, value: current_user.id
  .row
    .large-2.columns
      = f.submit 'Save', class: 'button tiny'
      = link_to 'Back', dependents_path, class: 'button tiny'

app/views/dependents/edit.html.haml
%h1 Editing dependent

= render 'form'

= link_to 'Show', @dependent
\|
= link_to 'Back', dependents_path

app/views/dependents/index.html.haml
%h1 My Dependents

%table
  %thead
    %tr
      %th First name
      %th Last name
      %th Date of birth
      %th
      %th

  %tbody
    - @dependents.each do |dependent|
      %tr
        %td= dependent.first_name
        %td= dependent.last_name
        %td= dependent.date_of_birth
        %td= link_to 'Edit', edit_dependent_path(dependent)
        %td= link_to 'Delete', dependent, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Dependent', new_dependent_path, class: 'button'

app/views/dependents/new.html.haml
%h1 New dependent

= render 'form'

app/views/dependents/show.html.haml
%p#notice= notice

%p
  %b First name:
  = @dependent.first_name
%p
  %b Last name:
  = @dependent.last_name
%p
  %b Date of birth:
  = @dependent.date_of_birth

= link_to 'Edit', edit_dependent_path(@dependent)
\|
= link_to 'Back', dependents_path

app/views/layouts/application.haml
!!!
%html{lang: "en"}
  %head
    %meta{charset: "utf-8"}/
    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "Medicine Reminder"
    = stylesheet_link_tag    "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    .row
  .large-3.columns
    %h1
      Medicine Reminder

= render 'shared/header'
/ First Band (Slider)
.row
  .large-12.columns

/ Three-up Content Blocks
.row
  = yield

= render 'shared/footer'

app/views/shared/_footer.haml
%footer.row
  .large-12.columns
    %hr/
    .row
      .large-6.columns
        %p &copy; Copyright no one at all.
      .large-6.columns
        %ul.inline-list.right
          %li
            %a{:href => "#"} Link 1
          %li
            %a{:href => "#"} Link 2
          %li
            %a{:href => "#"} Link 3
          %li
            %a{:href => "#"} Link 4


    %a.exit-off-canvas
    / / %p.notice= notice
    / %p.alert= alert
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = javascript_include_tag "vendor/modernizr"
    / = javascript_include_tag :defaults

app/views/shared/_header.haml
.large-9.columns
  - if current_user
    %ul.right.button-group
      %li= link_to "Dependents", dependents_path, :class => 'button tiny'
      %li= link_to "Medications", "#", :class => 'button tiny'
      %li= link_to "Doctors", "#", :class => 'button tiny'
      %li= link_to "Pharmacies", "#", :class => 'button tiny'
      %li= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'button tiny'
  - else
    %ul.right.button-group
      - if current_user
        %li= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'button tiny'
      - else
        %li= link_to "Login", new_user_session_path, :class => 'button tiny'

app/views/welcome/index.html.haml
- unless current_user
  .large-4.columns
    = image_tag("broken_glass.png", size: "400x300")
    %h4 The Problem
    %p In today's age it is hard enough to remember where you need to be on any given day. On top of that you have to remember when medications run. Not just when they run out, but to call before they run out to get a prescription for me.
  .large-4.columns
    = image_tag("hope.png", size: "400x300")
    %h4 The Hope
    %p What if there were something that could easily organize your medications? What if this could also remember when you were going to run out and remind you before hand.
  .large-4.columns
    = image_tag("sucess.png", size: "400x300")
    %h4 The Solution
    %p Medicine Reminder can help you. We will remember all your prescriptions for you. We will remind you to take your medication and we will remind you when you need to get more (before you run out of it). Oh, and we also track how this medication is effecting you.
  / Call to Action Panel
  - unless current_user
    .row
      .large-12.columns
        .panel
          %h4 Get Started!
          .row
            .large-9.columns
              %p It's free, so what are you waiting for?
            .large-3.columns
              =link_to "Register", new_user_registration_path, class: 'radius button right'